<?php require "logic/display-users.php" ?>

<table class="col my-5 table table-striped">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom d'utilisateur
            </th>
            <th>
                Email
            </th>
            <th>
                Mot de passe
            </th>
            <th>
                Rôle
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($usersList as $userInstance) {
            echo <<<HTML
                    <tr>
                        <td>{$userInstance->getId()}</td>
                        <td>{$userInstance->getUsername()}</td>
                        <td>{$userInstance->getPassword()}</td>
                        <td>{$userInstance->getEmail()}</td>
                        <td>{$userInstance->getRole()}</td>
                        <td>
                            <a href="logic/delete-user.php?id={$userInstance->getId()}" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
                        </td>
                    </tr>
                HTML;
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom d'utilisateur
            </th>
            <th>
                Email
            </th>
            <th>
                Mot de passe
            </th>
            <th>
                Rôle
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </tfoot>
</table>